//
//  PingPongPresenter.m
//  SBRF-UIKit
//
//  Created Artem Balashov on 29/03/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "PingPongPresenter.h"
#import "PingPongProtocols.h"
#import "CollisionDetectorService.h"

@interface PingPongPresenter () <PingPongPresenterInterface>
@property (strong, nonatomic) NSObject<PingPongWireframeInterface>* router;
@property (assign, nonatomic) BOOL isTopComputer;
@property (assign, nonatomic) BOOL isBottomComputer;
@property (assign, nonatomic) NSInteger bottomWins;
@property (assign, nonatomic) NSInteger topWins;
@property (assign, nonatomic) CGFloat ballDx;
@property (assign, nonatomic) CGFloat ballDy;
@end

@implementation PingPongPresenter

- (instancetype)initWithView:(NSObject<PingPongView>*)view router:(NSObject<PingPongWireframeInterface>*)router {
    self = [super init];
    if (self) {
        _view = view;
        _router = router;
    }
    return self;
}

- (void)viewDidAppear {
    //Default implementation
}

- (void)viewDidDissappear {
    //Default implementation
}

- (void)viewDidLoad {
    [self.view displayMenu];
    [self.view displayGameOverlay];
}

- (void)viewWillAppear {
    [self.view displayMenu];
    [self.view displayGameOverlay];
}

- (void)viewWillDissappear {
    //Default implementation
}

- (void)didSelectSettings {
    [self.view displayMenu];
    [self.view hideGameOverlay];
    [self.view displaySettings];
}

- (void)didSelectClearWinsButton
{
    [AppSettings setTopWins:0];
    [AppSettings setBottomWins:0];
}


- (void)didSelectStartGame {
    [self.view hideMenu];
    
}

- (void)didSelectMenuButton {
    [self.view pauseGame];
    [self.view displayMenu];
    [self.view hideSettings];
    [self.view displayGameOverlay];
}

@end
