//
//  PingPongAssembly.m
//  SBRF-UIKit
//
//  Created Artem Balashov on 29/03/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "PingPongAssembly.h"
#import "PingPongViewController.h"
#import "PingPongPresenter.h"
#import "PingPongProtocols.h"
#import "PingPongRouter.h"

@interface PingPongAssembly ()

@end

@implementation PingPongAssembly

+ (UIViewController *)createModule {
    PingPongViewController *view = [[PingPongViewController alloc] init];
    PingPongRouter *router = [[PingPongRouter alloc] init];
    PingPongPresenter *presenter = [[PingPongPresenter alloc] initWithView:view router:router];
    view.presenter = presenter;
    router.viewController = view;
    return view;
}

@end
