//
//  PingPongAssembly.h
//  SBRF-UIKit
//
//  Created Artem Balashov on 29/03/2019.
//  Copyright © 2019 pockerhead. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <UIKit/UIKit.h>

@interface PingPongAssembly: NSObject

+ (UIViewController *)createModule;

@end
